---
--- Generated by Luanalysis
--- Created by 12897.
--- DateTime: 2023/5/25 12:12
---
-- 参数传入优惠券id和用户id
local voucherId = ARGV[1]
local userId = ARGV[2]
--- new.新增orderId
local orderId = ARGV[3]
-- 获取该优惠券在redis的库存key和订单key
local seckillStockKey = "seckill:stock:" .. voucherId
local seckillOrderKey = "seckill:order:" .. voucherId
-- 判断库存是否充足
if (tonumber(redis.call("get", seckillStockKey)) <= 0) then
    return 1
end
-- 判断用户是否下过单，如果返回值为1，则该用户下过单
if (tonumber(redis.call("sismember", seckillOrderKey, userId)) == 1) then
    return 2
end
-- 库存-1，把用户id加入订单set集合
redis.call("incrby", seckillStockKey, -1)
redis.call("sadd", seckillOrderKey, userId)
--- new.如果创建订单成功就把订单数据放入stream（这里orderId在订单表是主键所以用key叫做id就行）
redis.call("xadd", "stream.orders", "*", "voucherId", voucherId, "userId", userId, "id", orderId)
return 0
