---
--- Generated by Luanalysis
--- Created by 12897.
--- DateTime: 2023/5/23 16:41
---
-- 如果值(uuid-线程id)一样，就删除该锁(key)
if (redis.call("get",KEYS[1]) == ARGV[1]) then
    return redis.call("del", KEYS[1])
end
-- 否则就返回0
return 0
